[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
gpui = { git = "https://github.com/zed-industries/zed", features = ["wayland"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
# Optional, for default bundled assets
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[workspace.dependencies.gpui_platform]
git = "https://github.com/zed-industries/zed"
features = ["font-kit", "wayland"]

[workspace.metadata.crane]
name = "taskforge"
