[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
circular-buffer.workspace = true
confy.workspace = true
enum-iterator.workspace = true
iced = { workspace = true, features = ["tokio"] }
iced_aw.workspace = true
iced_fonts = { workspace = true, features = ["advanced_text", "lucide"] }
open.workspace = true
plotters.workspace = true
plotters-iced.workspace = true
serde.workspace = true
sysinfo.workspace = true
system = { path = "../system" }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
